### ISSUE TITLE
License to build a comercial product?

### ISSUE THREAD

**Issue by paulocoutinhox** [opentibia/yatc#4]
Hi,

What is the license to build a comercial product with this client and the ot server? 

There is any problem?

Thanks for any information.

**Comment by ivucica** [comment]
GNU GPLv2 license is pretty clear. Please read it carefully.  This is a
difficult legal topic you are requesting non-professionals to answer, and
it is unfair that you are requesting us to spend time explaining something
that takes a lot of time to evaluate and explain -- especially since the
GPLv2 text is clear, and even if it isn't, there is a lot of information
about interpreting GPLv2 available online.

I recommend you to read and understand the license yourself, and to talk to
a lawyer in any jurisdiction you want to distribute your commercial product
into. GPLv2 has been te

Nonetheless, because I am feeling generous today, I will paraphrase the
most important aspects of it to help you out. This is nonexhaustive and not
legally binding on me or any other authors of YATC, OpenTibia Server or
other projects in this org.

- You are allowed to distribute the source code.
- You are allowed to distribute the binary code.
- Any recipient of the source code is free to redistribute it.
- Any recipient of the binary code is free to redistribute it.
- When you distribute the binary code, *ANYONE* receiving the binary code
*MUST* be freely supplied the source code *UPON WRITTEN REQUEST* for the
next 3 years (or it could be 2 -- please read the text of the license)
after the person received the binary code.
  - It is your duty as a distributor of GPLv2 to ensure you can reasonably
comply with these written requests.
  - GPLv2 requires you to offer to send the *source* code for cost no
larger than the medium or postage.
  - The cheapest way for you to comply is to simply publish the source code
online.
- Anyone who distributes the binary code from you must also distribute the
source code upon written request. (They may therefore come and ask you for
the binary.)
- Anyone who receives the source code *MUST BE PERMITTED* to redistribute
it under the same license as under which you received it (i.e. they can
freely redistribute it, under GPLv2).
- There are no restrictions on whether you sell the binary or otherwise
earn money -- but anyone receiving the binary may request the source code,
and they may redistribute the binary as well.
- Any code you dynamically or statically link with falls under GPLv2. While
code written in a scripting language is not (to my knowledge) considered
linked dynamically or statically and hence does not have to be opened up,
anything written in C++ and tied into YATC (or main OpenTibia Server
binary) must be distributed under GPLv2 i.e. must be opened up.
  - Code under LGPLv2 can be relicensed under GPLv2. This is why GLICT can
be linked with YATC.
  - Code under MIT or BSD 2-clause can be relicensed under GPLv2.
  - Proprietary code from your employer, which you don't own, likely
cannot, and should not be combined with GPLv2 code that you choose to
distribute.
- Lua scripts in OpenTibia Server are, I think, licensed under GPLv2, but
your scripts written in Lua don't have to be.
- You are required to both say who the original authors are (keep the
copyright notices!), and that you have made a modification (for example, by
adding your own appropriate copyright notice).

Note that GPLv2 mainly affects code that you distribute. If you run
OpenTibia Server on your systems and never ship the binary to users, there
are no recipients of binary or source code, hence you do not have to ship
your modifications.

It is highly unlikely you can utilize YATC in a useful fashion without
distributing it to end users, but if you find a way, you can technically
run a service based on portions of YATC source code without having to offer
to send the source code upon a written request.

An easy way to comply with GPLv2 is to simply publish the source code
whenever you distribute the binary code. The easiest way to do this is to
publish a version control repository publicly.

Note that none of the above prohibits you from commercially profiting off
of YATC or OpenTibia Server. It's just that your business model likely
cannot reasonably involve charging for the download. You are free to charge
for, e.g., subscription to your servers.

It is likely also difficult for you to run a server and ship a locked-down
YATC-based client that will be required to connect to your service: any of
the recipients of your modified YATC is free to request you open it
up, whereupon they can make modifications to it. This doesn't, of course,
prevent you from managing user accounts commercially.

Please note that YATC does not include any useful graphical assets. Assets
owned by a certain German company are just that, proprietary to them, and
there's no additional permission to distribute them just because GPLv2
allows you to distribute YATC itself. Should you produce your own .pic,
.dat and .spr files, it does not have to be licensed under GPLv2: only the
code linked with and compiled into the YATC binary needs to be licensed or
relicenseable under GPLv2.

---

As for my own (non-legally-binding) thoughts?

Please make money off of your own work. The portions of YATC that I wrote
are public because I am happy to allow the world to learn, study and
contribute back to the commons. This informed my choice of GPLv2 when I was
starting off with YATC.

I don't have a problem with you charging a subscription for your instance
of OTserv (especially if you invested time into building a map, into
writing scripts). And if you created enough graphics you can ship with YATC
to make it playable? Great! Please do ship YATC binaries freely. But I will
ask you to publish the source code. I want to learn from your modifications
as well. Publishing your modifications is a way to repay me (and other
authors) for my considerable time investment into YATC.

I cannot relicense YATC for you under a proprietary license for any
monetary compensation, because I am not the sole author of the code. This
is working as intended: the correct repayment is contributing to the
commons, and it is very cheap for you: you are making the changes anyway,
why not simply publish them? I can change the license of my contributions,
but combining such relicensed code with the rest of the work contributed by
others would be difficult for both you as the recipient and me as the
distributor (and later you as the distributor).

I contributed very little to OpenTibia Server, but should you distribute
the binaries, it's very trivial to publish the source code too. You are not
required to distribute the binaries (and therefore the source code) to
simply run the service.

Note that neither OTserv nor YATC are licensed under AGPL, hence a mere
network connection is not sufficient to allow users to request the source
code of your running OTserv or YATC-derived binary.

> Message ID: ***@***.***>
>
I am not a lawyer, and GPLv2 text has the final say in the matter (except
for the courts, of course, should it come to that).
